import type { Metadata } from "next";
import { Toaster } from '@/components/ui/sonner';
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from '@/components/app-sidebar';
import { Separator } from '@/components/ui/separator';
import { Breadcrumble } from '@/components/breadcrumb-link';


export const metadata: Metadata = {
    title: "Events",
    description: "Generated by create next app",
};

export default function RootLayout ( {
    children,
}: Readonly<{
    children: React.ReactNode;
}> ) {
    return (
        <>
            <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                    <header className="flex h-12 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-10">
                        <div className="flex items-center gap-2 px-4">
                            <SidebarTrigger className="-ml-1" />
                            <Separator orientation="vertical" className="mr-2 h-4" />
                            <Breadcrumble />
                        </div>
                    </header>
                    {children}
                    <Toaster />
                </SidebarInset>
            </SidebarProvider>

        </>
    );
}
